#Requires -Version 5.1
<#
.SYNOPSIS
  Compiles the Inno Setup installer from artifacts\release\win-x64.

.PARAMETER Version
  Semantic version (e.g. 0.0.1). Defaults from version.json.

.PARAMETER Channel
  Release channel (beta / release). Defaults from version.json.
#>
param(
    [Parameter(Mandatory = $false)]
    [string]$Version = "",
    [Parameter(Mandatory = $false)]
    [string]$Channel = ""
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

. (Join-Path $Root "scripts\Version-Common.ps1")
$vi = Get-ChyguiSlideVersionInfo -Root $Root
if ([string]::IsNullOrWhiteSpace($Version)) { $Version = $vi.Version }
if ([string]::IsNullOrWhiteSpace($Channel)) { $Channel = $vi.Channel }
$label = if ($Channel -eq "release") { $Version } else { "$Version-$Channel" }
$displayName = if ($Channel -eq "release") { "Чугуй Слайды" } else { "Чугуй Слайды ($Channel)" }
$publisher = "Чугуй Слайды"
$groupName = "Чугуй Слайды"

$IssPath = Join-Path $Root "installer\ChyguiSlide.iss"
$DefinesPath = Join-Path $Root "installer\GeneratedDefines.iss"
$PublishDir = Join-Path $Root "artifacts\release\win-x64"
$Launcher = Join-Path $PublishDir "ChyguiSlide.exe"
$OutSetup = Join-Path $Root "artifacts\release\ChyguiSlide-$label-Setup.exe"

if (-not (Test-Path $IssPath)) {
    throw "Inno script not found: $IssPath"
}

if (-not (Test-Path $Launcher)) {
    throw "Publish folder missing or incomplete: $PublishDir (run Publish-Release.ps1 first)"
}

function Find-ISCC {
    $fromPath = Get-Command ISCC.exe -ErrorAction SilentlyContinue
    if ($fromPath) {
        return $fromPath.Source
    }

    $candidates = @(
        "${env:LOCALAPPDATA}\Programs\Inno Setup 6\ISCC.exe",
        "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
        "${env:ProgramFiles}\Inno Setup 6\ISCC.exe",
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
        "C:\Program Files\Inno Setup 6\ISCC.exe"
    )

    foreach ($path in $candidates) {
        if ($path -and (Test-Path $path)) {
            return $path
        }
    }

    return $null
}

$iscc = Find-ISCC
if (-not $iscc) {
    Write-Host ""
    Write-Host "Inno Setup 6 (ISCC.exe) не найден." -ForegroundColor Red
    Write-Host "Установите Inno Setup 6 с русским языком:" -ForegroundColor Yellow
    Write-Host "  https://jrsoftware.org/isinfo.php"
    Write-Host "Затем повторите сборку."
    throw "ISCC.exe not found"
}

# Кириллицу нельзя надёжно передать через /D в командной строке —
# пишем UTF-8 BOM include, который читает ChyguiSlide.iss.
$utf8Bom = New-Object System.Text.UTF8Encoding $true

# Конвертируем кириллицу в Unicode escape-последовательности для Inno Setup (#xxxx)
function ConvertToInnoUnicode($str) {
    $result = New-Object System.Text.StringBuilder
    foreach ($char in $str.ToCharArray()) {
        if ($char -ge 128) {
            $result.Append("#{0:X4}" -f [int]$char) | Out-Null
        } else {
            $result.Append($char) | Out-Null
        }
    }
    return $result.ToString()
}

$displayNameEsc = ConvertToInnoUnicode $displayName
$publisherEsc = ConvertToInnoUnicode $publisher
$groupNameEsc = ConvertToInnoUnicode $groupName

$defines = @"
; Auto-generated by Build-Installer.ps1 — do not edit.
#ifndef MyAppVersion
  #define MyAppVersion "$Version"
#endif
#ifndef MyAppVersionLabel
  #define MyAppVersionLabel "$label"
#endif
#ifndef MyAppDisplayName
  #define MyAppDisplayName "$displayNameEsc"
#endif
#ifndef MyAppPublisher
  #define MyAppPublisher "$publisherEsc"
#endif
#ifndef MyAppGroupName
  #define MyAppGroupName "$groupNameEsc"
#endif
"@

# Записываем в UTF-8 с BOM для совместимости с Inno Setup
[System.IO.File]::WriteAllText($DefinesPath, $defines, $utf8Bom)

# Сам .iss тоже должен быть UTF-8 с BOM, иначе DefaultGroupName и т.п. ломаются.
$issBytes = [System.IO.File]::ReadAllBytes($IssPath)
if ($issBytes.Length -lt 3 -or $issBytes[0] -ne 0xEF -or $issBytes[1] -ne 0xBB -or $issBytes[2] -ne 0xBF) {
    $issText = [System.IO.File]::ReadAllText($IssPath)
    [System.IO.File]::WriteAllText($IssPath, $issText, $utf8Bom)
    Write-Host "Normalized ChyguiSlide.iss to UTF-8 BOM."
}

Write-Host "=== Building installer $label ($displayName) ===" -ForegroundColor Cyan
Write-Host "ISCC: $iscc"
Write-Host "Script: $IssPath"

if (Test-Path $OutSetup) {
    Remove-Item $OutSetup -Force
}

# Только ASCII-параметры в командной строке; имена — из GeneratedDefines.iss
& $iscc `
    "/DMyAppVersion=$Version" `
    "/DMyAppVersionLabel=$label" `
    $IssPath
if ($LASTEXITCODE -ne 0) {
    throw "ISCC failed with exit code $LASTEXITCODE"
}

if (-not (Test-Path $OutSetup)) {
    throw "Expected installer not found: $OutSetup"
}

$sizeMb = [math]::Round((Get-Item $OutSetup).Length / 1MB, 1)
Write-Host ""
Write-Host "Installer ready." -ForegroundColor Green
Write-Host "  Setup: $OutSetup"
Write-Host "  Size:  $sizeMb MB"
